name: CI

on:
  push:
    branches:
      - master
      - feature/homepage
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check website exists
        run: test -f index.html

      - name: Show success
        run: echo "Website test passed!"
